Make OutPoint fields pub
str4d/librustzcash pull request #5
Opened 2019-09-10 17:07 UTC by adityapk00

Make OutPoint fields pub so light clients can build transparent inputs

2019-09-10 17:22 UTC, str4d commented on zcash_primitives/src/transaction/components.rs
> +    pub n: u32,
In what context will these be set directly instead of being read or written? I'm personally more inclined towards having `OutPoint::new(hash: [u8; 32], n: u32)` instead of exposing the values, so that an `OutPoint` read from a transaction can't be mutated accidentally. But I'm interested to know if there's a use case for direct mutation.

2019-09-10 17:26 UTC, adityapk00 commented on zcash_primitives/src/transaction/components.rs
> +    pub n: u32,
I guess you're right. They don't need to be mutated, just be constructed from the `hash` and `n` fields. 

I have 2 use cases for `OutPoint::new`:
1. In tests, I want to create a `OutPoint` manually from hex-encoded test vectors
2. ZecWalletLight is fetching these from lightwalletd, and they come as protobuf fields, from which I have to contruct an `OutPoint`.

2019-09-10 17:33 UTC, adityapk00 commented
OK, Updated the PR to do `OutPoint::new`

2019-10-05 22:16 UTC, str4d requested changes
@adityapk00 could you please squash in a `cargo fmt`? There are missing spaces that will cause CI to fail in my PR once this is merged into my branch.

2019-10-08 18:58 UTC, zancas commented on zcash_primitives/src/transaction/components.rs
> +    pub n: u32,
Even if the `hash` and `n` fields were public they would be immutable.

2019-10-14 20:01 UTC, str4d commented on zcash_primitives/src/transaction/components.rs
> +    pub n: u32,
@zancas only where the `OutPoint` is held as an immutable reference, and given that this function is creating a standalone `OutPoint`, that is by definition not the case (leaving it instead to the caller to enforce).

2019-10-14 20:31 UTC, str4d commented
bump @adityapk00 :)

(If still blocked next week I'll time out and do this myself.)

2019-10-14 20:37 UTC, str4d approved these changes

2019-10-14 20:37 UTC, merged

2019-10-15 19:24 UTC, zancas commented on zcash_primitives/src/transaction/components.rs
> +    pub n: u32,
You're correct.

2019-10-15 21:15 UTC, zancas commented on zcash_primitives/src/transaction/components.rs
> +    pub n: u32,
This interaction enhanced my model of Rust.   Thanks!